version: '2'

services:
  broker:
    image: redis:latest
    container_name: broker
    ports:
      - "46379:6379"
  indexer:
    build:
      context: ./indexer
    container_name: indexer
    command: logstash -f /etc/logstash/conf.d/logstash.conf    
    links:
      - broker
      - elasticsearch   
  elasticsearch:
    build:
      context: ./elasticsearch      
    container_name: elasticsearch    
    ports:
      - "49200:9200"
  kibana:
    build:
      context: ./kibana      
    container_name: kibana    
    ports:
      - "45601:5601"
    links:
      - elasticsearch